name: ore_pool_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  path_provider: ^1.6.24
  font_awesome_flutter: ^8.10.0
  
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  scoped_model: ^1.1.0
  url_launcher: ^5.7.10
  flutter_easyloading: ^2.2.1
  flutter_swiper: ^1.1.6

  webview_flutter: ^1.0.7
  graphic: ^0.2.1
  flutter_echarts: ^1.5.0

  google_fonts: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/login_logo.png
